### ISSUE TITLE
rooms::list_rooms::v1::Request failed - deserialization failed: invalid type: integer `0`

### ISSUE THREAD

**Issue by avp90** [ruma/synapse-admin-api#14]
The deserialization of the list rooms response (request `synapse_admin_api::rooms::list_rooms::v1::Request`) is failing with following message:
```
deserialization failed: invalid type: integer `0`, expected a boolean at line 1 column 354
```

Following properties should be handled with [serde/boolean_as_uint](https://github.com/ruma/synapse-admin-api/blob/main/src/serde/boolean_as_uint.rs):
- federatable
- public

**Comment by jplatte** [comment]
Should be fixed by c82d3ce1b46fcc1ed76e1af556677e370220968b. Let me know if it still doesn't work.
